services:
  postgres:
    image: arm32v7/postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backendnetwork
networks:
  backendnetwork:
    external: true
volumes:
  postgres_data: {}